---
apiVersion: v1
kind: Namespace

metadata:
  name: nwapp
  labels:
    version: v1
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwdb-config
  namespace: nwapp

data:
  db_password: changeit
  db_host: nwdb-svc.nwapp.svc.cluster.local
---
apiVersion: v1
kind: Secret

metadata:
  name: nwdb-secret
  namespace: nwapp

# base64 encoding of password: nwdb
data:
  db_password: bndkYg==