---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nwapp-deploy
  namespace: nwapp
  labels:
    name: nwapp
    version: v1

spec:
  # number of pods
  replicas: 3
  selector:
    matchLabels:
      name: nwapp
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    # pod template
    metadata:
      name: nwapp-pod
      labels:
        name: nwapp
        version: v1
    spec:
      containers:
        - name: nwapp-container
          image: stackupiss/northwind-app:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "nwdb-secret"
                  key: "db_password"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: "nwdb-config"
                  key: "db_host"
            - name: DB_PORT
              value: "3306"
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
          ports:
            - name: nwapp-port
              containerPort: 3000