version: '3'

networks:
  appnet:

volumes:
  appvol:

services:
  nwdb:
    image: metamagpie/nwdb
    build:
      context: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=changeit
    networks:
      - appnet
    volumes:
      - appvol:/var/lib/mysql
  nwapp:
    image: metamagpie/nwapp
    build:
      context: ./server
    environment:
      - DB_HOST=nwdb
    ports:
      - 80:3000
    networks:
      - appnet
